CREATE TABLE Players (
    Id INT IDENTITY PRIMARY KEY,
    Username NVARCHAR(64) NOT NULL UNIQUE,
    CurrentRank NVARCHAR(32) NOT NULL,
    EligibleRank NVARCHAR(32) NOT NULL,
    Status INT NOT NULL,
    LastSeen DATETIMEOFFSET NOT NULL,
    LastSynced DATETIMEOFFSET NULL,
    StoredPetCount INT NOT NULL,
    ManualPetOverride INT NULL
);

CREATE TABLE PlayerSnapshots (
    Id INT IDENTITY PRIMARY KEY,
    PlayerId INT NOT NULL FOREIGN KEY REFERENCES Players(Id),
    Timestamp DATETIMEOFFSET NOT NULL,
    TotalLevel INT NOT NULL,
    EHB FLOAT NOT NULL,
    EHP FLOAT NOT NULL,
    Collections INT NOT NULL,
    PetCount INT NOT NULL
);

CREATE TABLE PromotionCandidates (
    Id INT IDENTITY PRIMARY KEY,
    PlayerId INT NOT NULL FOREIGN KEY REFERENCES Players(Id),
    OldRank NVARCHAR(32) NOT NULL,
    NewRank NVARCHAR(32) NOT NULL,
    Reason NVARCHAR(2048) NOT NULL,
    Status INT NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL
);

CREATE TABLE LifecycleEvents (
    Id INT IDENTITY PRIMARY KEY,
    PlayerId INT NOT NULL FOREIGN KEY REFERENCES Players(Id),
    EventType NVARCHAR(128) NOT NULL,
    MetadataJson NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(64) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL
);
